title: Madeeha Umar # your name (or website title) here
logo: "/images/Profile Pic with light grey background.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data analyst who loves data. With my expertise in SQL, Tableau, and Excel, I effectively communicate and solve problems by transforming data into valuable insights and enabling businesses to achieve accelerated growth.
  <br><br>
  <a href="https://www.linkedin.com/in/madeehaumar/">View My LinkedIn Profile</a> 

  

  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
